# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Disform < Formula
  desc "Declarative Discord server management. Like Terraform, but for Discord."
  homepage "https://github.com/joshdholtz/disform"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joshdholtz/disform/releases/download/v0.1.1/disform_0.1.1_darwin_amd64.tar.gz"
      sha256 "f20938f5130bf4c37afcecb36e462fb123601495ad38f18265e411be05d22018"

      define_method(:install) do
        bin.install "disform"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joshdholtz/disform/releases/download/v0.1.1/disform_0.1.1_darwin_arm64.tar.gz"
      sha256 "312e153000996df32c317e95de21b8792fe82e399b086cdc6247e3be7244be0b"

      define_method(:install) do
        bin.install "disform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshdholtz/disform/releases/download/v0.1.1/disform_0.1.1_linux_amd64.tar.gz"
      sha256 "98e4a83cfc1b0a1a6eb758b9fb04dc9b59b006a313d7e4614c4a5dcae0eb86d4"
      define_method(:install) do
        bin.install "disform"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshdholtz/disform/releases/download/v0.1.1/disform_0.1.1_linux_arm64.tar.gz"
      sha256 "2a7bf9b5951ceb78390c735e9efc7b7490a0f153dcf6ab3eff41780015b9dbf9"
      define_method(:install) do
        bin.install "disform"
      end
    end
  end

  test do
    system "#{bin}/disform version"
  end
end
