# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Disform < Formula
  desc "Declarative Discord server management. Like Terraform, but for Discord."
  homepage "https://github.com/joshdholtz/disform"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joshdholtz/disform/releases/download/v0.1.6/disform_0.1.6_darwin_amd64.tar.gz"
      sha256 "06d7c05e4195555b750b876274f6d3dab293a5ae07456ff3f90ba7fe217f253e"

      define_method(:install) do
        bin.install "disform"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joshdholtz/disform/releases/download/v0.1.6/disform_0.1.6_darwin_arm64.tar.gz"
      sha256 "0db8edd23389a8eee69ea2f86bac43290ab599b63d1899e26e10e33dfd9bca8c"

      define_method(:install) do
        bin.install "disform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshdholtz/disform/releases/download/v0.1.6/disform_0.1.6_linux_amd64.tar.gz"
      sha256 "3a50cc63dd220a9effdefb7bb9670ad7e78eb4aca3e34493cb0fe3d7b1e45021"
      define_method(:install) do
        bin.install "disform"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshdholtz/disform/releases/download/v0.1.6/disform_0.1.6_linux_arm64.tar.gz"
      sha256 "aa93da2c1c8d1796f1f815a7dbd33de3e00cc83308d950f7e541473963bdacfe"
      define_method(:install) do
        bin.install "disform"
      end
    end
  end

  test do
    system "#{bin}/disform version"
  end
end
